import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "@/components/ui/provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const manrope = localFont({
    src: [
        { path: "./fonts/Manrope-ExtraLight.ttf", weight: "200", style: "normal" },
        { path: "./fonts/Manrope-Light.ttf", weight: "300", style: "normal" },
        { path: "./fonts/Manrope-Regular.ttf", weight: "400", style: "normal" },
        { path: "./fonts/Manrope-Medium.ttf", weight: "500", style: "normal" },
        { path: "./fonts/Manrope-SemiBold.ttf", weight: "600", style: "normal" },
        { path: "./fonts/Manrope-Bold.ttf", weight: "700", style: "normal" },
        { path: "./fonts/Manrope-ExtraBold.ttf", weight: "800", style: "normal" },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${manrope.className}`}
            >
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}
